if(WIN32)
	option(USE_RUNJOBS_PARALLEL_BUILDING "Build configurations in parallel using RunJobs" ON)
	
	if ( USE_RUNJOBS_PARALLEL_BUILDING ) 
		if (NOT RUNJOBS_EXECUTABLE)
			if (CMAKE_SIZEOF_VOID_P MATCHES 8)
				FIND_PROGRAM(RUNJOBS_EXECUTABLE NAME RunJobs64.exe PATHS /RunJobs X:/RunJobs/ $ENV(RUN_JOBS_DIR) )
			else (CMAKE_SIZEOF_VOID_P MATCHES 8)
				FIND_PROGRAM(RUNJOBS_EXECUTABLE NAME RunJobs.exe PATHS /RunJobs X:/RunJobs/ $ENV(RUN_JOBS_DIR) )
			endif (CMAKE_SIZEOF_VOID_P MATCHES 8)
		endif(NOT RUNJOBS_EXECUTABLE)
		if ( (${RUNJOBS_EXECUTABLE} MATCHES "RUNJOBS_EXECUTABLE_NOTFOUND") OR (NOT EXISTS ${RUNJOBS_EXECUTABLE}) )
			message( FATAL_ERROR "Please set the location of the RunJobs executable or disable the RunJobs feature." )
		endif ( (${RUNJOBS_EXECUTABLE} MATCHES "RUNJOBS_EXECUTABLE_NOTFOUND") OR (NOT EXISTS ${RUNJOBS_EXECUTABLE}))
		
	endif( USE_RUNJOBS_PARALLEL_BUILDING )
	
endif(WIN32)